# Generated by Django 5.0.6 on 2024-06-14 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garaz1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vozidlo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jmeno', models.CharField(error_messages={'blank': 'Jméno vozidla musí být vyplněno'}, help_text='Zadejte jméno vozidla', max_length=80, verbose_name='Jméno vozidla')),
                ('vyrobce', models.CharField(error_messages={'blank': 'Název výrobce musí být vyplněn'}, help_text='Zadejte výrobce vozidla', max_length=50, verbose_name='vyrobce')),
                ('typ_vozidla', models.CharField(error_messages={'blank': 'Typ vozidla musí být vyplněn'}, help_text='Auto,moto,kamion,traktor', max_length=50, verbose_name='typ')),
                ('cena', models.IntegerField(help_text='v korunách')),
                ('hmotnost', models.IntegerField(help_text='v kg')),
            ],
            options={
                'verbose_name': 'vozidlo',
                'verbose_name_plural': 'vozidlo',
                'ordering': ['vyrobce'],
            },
        ),
    ]
