# Generated by Django 5.0.6 on 2024-06-16 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garaz1', '0002_vozidlo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ridic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=255)),
                ('lastname', models.CharField(max_length=255)),
                ('datum_narozeni', models.DateField()),
                ('telefon', models.CharField(max_length=9)),
                ('pojistovna', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Member',
        ),
        migrations.AlterField(
            model_name='vozidlo',
            name='jmeno',
            field=models.CharField(error_messages={'blank': 'Model vozidla musí být vyplněno'}, help_text='Zadejte model vozidla', max_length=80, verbose_name='Model vozidla'),
        ),
        migrations.AddField(
            model_name='ridic',
            name='vozidlo',
            field=models.ManyToManyField(to='garaz1.vozidlo', verbose_name='vozidlo'),
        ),
    ]
