# Generated by Django 4.2.13 on 2024-06-17 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garaz1', '0003_ridic_delete_member_alter_vozidlo_jmeno_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brzdy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('znacka', models.CharField(max_length=255)),
                ('model', models.CharField(max_length=255)),
                ('efektivita', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Motor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('znacka', models.CharField(max_length=255)),
                ('model', models.CharField(max_length=255)),
                ('valce', models.CharField(max_length=255)),
                ('obsah', models.IntegerField()),
                ('vykon', models.CharField(max_length=255)),
                ('turbo', models.BooleanField(default=False)),
                ('palivo', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Odpruzeni',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('znacka', models.CharField(max_length=255)),
                ('model', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Pneu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('znacka', models.CharField(max_length=255)),
                ('model', models.CharField(max_length=255)),
                ('letni', models.BooleanField(default=True)),
            ],
        ),
    ]
