# Generated by Django 4.2.13 on 2024-06-17 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garaz1', '0004_brzdy_motor_odpruzeni_pneu'),
    ]

    operations = [
        migrations.AddField(
            model_name='vozidlo',
            name='brzdy',
            field=models.ManyToManyField(to='garaz1.brzdy', verbose_name='Brzdy'),
        ),
        migrations.AddField(
            model_name='vozidlo',
            name='motorizace',
            field=models.ManyToManyField(to='garaz1.motor', verbose_name='Motorizace'),
        ),
        migrations.AddField(
            model_name='vozidlo',
            name='odpruzeni',
            field=models.ManyToManyField(to='garaz1.odpruzeni', verbose_name='Odpruzeni'),
        ),
        migrations.AddField(
            model_name='vozidlo',
            name='pneu',
            field=models.ManyToManyField(to='garaz1.pneu', verbose_name='Pneu'),
        ),
    ]
